# Generated by Django 2.1.7 on 2019-12-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Мистецтво',
                'verbose_name_plural': 'Мистецтво',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=2000, verbose_name='Назва')),
                ('author', models.CharField(blank=True, default=None, max_length=2000, verbose_name='Автор')),
                ('publication', models.CharField(blank=True, db_index=True, default=None, max_length=200, verbose_name='Місце видання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('series', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Серія')),
                ('personality', models.CharField(blank=True, db_index=True, default=None, max_length=200, verbose_name='Персоналії')),
                ('additional', models.CharField(blank=True, db_index=True, default=None, max_length=200, verbose_name='Додатково')),
                ('isbn', models.CharField(blank=True, default=None, max_length=20, verbose_name='ISBN')),
                ('inventory_number', models.CharField(blank=True, default=None, max_length=200, verbose_name='Інвентарний номер')),
                ('cipher', models.CharField(blank=True, default=None, max_length=200, verbose_name='Шифр книги')),
                ('year', models.CharField(blank=True, default=None, max_length=200, verbose_name='Рік видання')),
                ('language', models.CharField(blank=True, db_index=True, default=None, max_length=200, verbose_name='Мова')),
                ('country', models.CharField(blank=True, db_index=True, default=None, max_length=200, verbose_name='Країна')),
                ('slug', models.SlugField(blank=True, max_length=2000)),
                ('art', models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Art', verbose_name='Мистецтво')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Місцезнаходження',
                'verbose_name_plural': 'Місцезнаходження',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(blank=True, max_length=200, verbose_name='Назва')),
                ('a', models.CharField(blank=True, default=None, max_length=200, verbose_name='Автор')),
                ('publ', models.CharField(blank=True, default=None, max_length=200, verbose_name='Місце видання')),
                ('add', models.CharField(blank=True, default=None, max_length=200, verbose_name='Додатково')),
                ('ser', models.CharField(blank=True, default=None, max_length=200, verbose_name='Серія')),
                ('pers', models.CharField(blank=True, max_length=200, verbose_name='Персоналії')),
                ('invnum', models.CharField(blank=True, max_length=200, verbose_name='Інвентарний номер')),
                ('yfr', models.CharField(blank=True, max_length=200, verbose_name='З року')),
                ('yto', models.CharField(blank=True, max_length=200, verbose_name='До року')),
                ('lang', models.CharField(blank=True, max_length=200, verbose_name='Мова')),
                ('cntr', models.CharField(blank=True, max_length=200, verbose_name='Країна')),
                ('art', models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Art', verbose_name='Мистецтво')),
                ('gr', models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Group', verbose_name='Групи')),
                ('plc', models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Place', verbose_name='Місцезнаходження')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='search',
            name='subj',
            field=models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Subject', verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='book',
            name='group',
            field=models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Group', verbose_name='Групи'),
        ),
        migrations.AddField(
            model_name='book',
            name='place',
            field=models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Place', verbose_name='Місцезнаходження'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Subject', verbose_name='Тематика'),
        ),
    ]
