# Generated by Django 2.1.2 on 2018-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0002_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VI', 'Вітчизняні'), ('IN', 'Іноземні'), ('PI', 'Періодика'), ('CA', 'Каталог')], db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Групи',
                'verbose_name_plural': 'Групи',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['country'], 'verbose_name': 'Мистецтво', 'verbose_name_plural': 'Мистецтво'},
        ),
    ]
