# Generated by Django 2.1.2 on 2018-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0003_auto_20181213_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
