# Generated by Django 2.1.2 on 2018-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0004_auto_20181213_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='art',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
