# Generated by Django 2.1.4 on 2018-12-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0006_auto_20181213_1638'),
        ('lgaapp', '0004_auto_20181213_1639'),
    ]

    operations = [
    ]
