# Generated by Django 2.1.2 on 2018-12-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0007_auto_20181214_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='art',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='lgaapp.Art', verbose_name='Мистецтво'),
        ),
    ]
