# Generated by Django 2.1.4 on 2018-12-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0007_merge_20181214_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='book',
            name='additional',
            field=models.CharField(db_index=True, default=None, max_length=200, verbose_name='Додатково'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, default=None, max_length=200, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='cipher',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, verbose_name='Шифр книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(db_index=True, default=None, max_length=200, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='book',
            name='groups',
            field=models.TextField(blank=True, verbose_name='Групи'),
        ),
        migrations.AddField(
            model_name='book',
            name='inventory_number',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, verbose_name='Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.TextField(blank=True, verbose_name='Мова'),
        ),
        migrations.AddField(
            model_name='book',
            name='object',
            field=models.CharField(db_index=True, default=None, max_length=200, verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='book',
            name='personality',
            field=models.CharField(db_index=True, default=None, max_length=200, verbose_name='Персоналії'),
        ),
        migrations.AddField(
            model_name='book',
            name='place',
            field=models.TextField(blank=True, verbose_name='Місцезнаходження'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(db_index=True, default=None, max_length=200, verbose_name='Видання'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, verbose_name='Серія'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.TextField(blank=True, verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=30, verbose_name='Рік видання'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterIndexTogether(
            name='book',
            index_together={('id', 'slug')},
        ),
    ]
