# Generated by Django 2.1.4 on 2018-12-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0009_auto_20181214_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.IntegerField(default=None, max_length=30, verbose_name='Інвентарний номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(default=None, null=True, verbose_name='Рік видання'),
        ),
    ]
