# Generated by Django 2.1.4 on 2018-12-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0011_auto_20181214_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name': 'Книги', 'verbose_name_plural': 'Книга'},
        ),
        migrations.AlterIndexTogether(
            name='book',
            index_together=set(),
        ),
    ]
