# Generated by Django 2.1.4 on 2018-12-14 12:27

from django.db import migrations, models
import lgaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0012_auto_20181214_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='art',
            field=models.CharField(default=None, max_length=200, verbose_name=lgaapp.models.Art),
        ),
        migrations.AddField(
            model_name='book',
            name='group',
            field=models.CharField(default=None, max_length=200, verbose_name=lgaapp.models.Group),
        ),
        migrations.AlterField(
            model_name='book',
            name='cipher',
            field=models.PositiveIntegerField(default=None, verbose_name='Шифр книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(default=None, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.PositiveIntegerField(default=None, verbose_name='Серія'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(default=None, max_length=200, verbose_name=lgaapp.models.Subject),
        ),
    ]
