# Generated by Django 2.1.4 on 2018-12-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0014_auto_20181214_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='art',
            field=models.ForeignKey(default=None, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Art', verbose_name='Мистецтво'),
        ),
        migrations.AlterField(
            model_name='book',
            name='group',
            field=models.ForeignKey(default=None, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Group', verbose_name='Групи'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(default=None, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Subject', verbose_name='Тематика'),
        ),
    ]
