# Generated by Django 2.1.4 on 2018-12-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0015_auto_20181214_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='groups',
        ),
    ]
