# Generated by Django 2.1.4 on 2018-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0017_auto_20181214_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='additional',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Додатково'),
        ),
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='book',
            name='personality',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Персоналії'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Видання'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.PositiveIntegerField(default='', verbose_name='Серія'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(default='', null=True, verbose_name='Рік видання'),
        ),
    ]
