# Generated by Django 2.1.4 on 2018-12-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0018_auto_20181214_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='additional',
            field=models.CharField(db_index=True, default=None, max_length=200, null=True, verbose_name='Додатково'),
        ),
        migrations.AlterField(
            model_name='book',
            name='art',
            field=models.ForeignKey(default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Art', verbose_name='Мистецтво'),
        ),
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(db_index=True, default=None, max_length=200, null=True, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='book',
            name='group',
            field=models.ForeignKey(default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Group', verbose_name='Групи'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='book',
            name='personality',
            field=models.CharField(db_index=True, default=None, max_length=200, null=True, verbose_name='Персоналії'),
        ),
        migrations.AlterField(
            model_name='book',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Місцезнаходження'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(db_index=True, default=None, max_length=200, null=True, verbose_name='Видання'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.PositiveIntegerField(default=None, verbose_name='Серія'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(default=None, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgaapp.Subject', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(default=None, null=True, verbose_name='Рік видання'),
        ),
    ]
