# Generated by Django 2.1.4 on 2018-12-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0020_auto_20181214_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.PositiveIntegerField(null=True, verbose_name='Серія'),
        ),
    ]
