# Generated by Django 2.1.4 on 2018-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0023_auto_20181214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Рік видання'),
        ),
    ]
