# Generated by Django 3.2.4 on 2021-06-27 15:08

from django.db import migrations


def load_predefined_subjects(apps, schema_editor):
	Subject = apps.get_model("lgaapp", "Subject")
	Subject(
		name='Наука і Культура',
	).save()
	Subject(
		name='Художня Література',
	).save()
	Subject(
		name='Книгознавство',
	).save()
	Subject(
		name='Культорологія',
	).save()
	Subject(
		name='Бібліографія',
	).save()
	Subject(
		name='Бібліотечна Справа',
	).save()
	Subject(
		name='Музеї',
	).save()
	Subject(
		name='Філософія',
	).save()
	Subject(
		name='Психологія',
	).save()
	Subject(
		name='Етика',
	).save()
	Subject(
		name='Релігія',
	).save()
	Subject(
		name='Історія',
	).save()
	Subject(
		name='Історія Львова',
	).save()
	Subject(
		name='Ентнологія. Етнографія. Фольклор',
	).save()


def load_predefined_arts(apps, schema_editor):
	Art = apps.get_model("lgaapp", "Art")
	Art(
		name='Живопис',
	).save()
	Art(
		name='Графіка',
	).save()
	Art(
		name='Скульптура',
	).save()
	Art(
		name='Архітектура',
	).save()
	Art(
		name='Декоративно-прикладне мистецтво',
	).save()
	Art(
		name='Фотомистецтво',
	).save()
	Art(
		name='Історія мистецтва',
	).save()
	Art(
		name='Сакральне мистецтво',
	).save()
	Art(
		name='Мініатюра',
	).save()
	Art(
		name='Теорія мистецтва',
	).save()
	Art(
		name='Музика',
	).save()
	Art(
		name='Театр',
	).save()
	Art(
		name='Кіно',
	).save()


def load_predefined_groups(apps, schema_editor):
	Group = apps.get_model("lgaapp", "Group")
	Group(
		name='Книги Вітчизняні',
	).save()
	Group(
		name='Книги іноземні',
	).save()
	Group(
		name='Періодика',
	).save()
	Group(
		name='Каталоги',
	).save()
	Group(
		name='Фонд Возницького',
	).save()
	Group(
		name='Каталоги-дублети',
	).save()


def load_predefined_places(apps, schema_editor):
	Place = apps.get_model("lgaapp", "Place")
	Place(
		name='Палац Потоцьких',
	).save()
	Place(
		name='Музей книги',
	).save()
	Place(
		name='Олеськ',
	).save()
	Place(
		name='Золочів',
	).save()


class Migration(migrations.Migration):
	dependencies = [
		('lgaapp', '0001_initial'),
	]

	operations = [
		migrations.RunPython(
			load_predefined_subjects,
		),
		migrations.RunPython(
			load_predefined_arts,
		),
		migrations.RunPython(
			load_predefined_groups,
		),
		migrations.RunPython(
			load_predefined_places,
		),

	]
