# Generated by Django 3.2.13 on 2022-06-01 14:57

from django.db import migrations


def updates_to_subjects(apps, schema_editor):
    Subject = apps.get_model("lgaapp", "Subject")

    ethnology = Subject.objects.get(name='Ентнологія. Етнографія. Фольклор')
    ethnology.name = 'Етнологія. Етнографія. Фольклор'
    ethnology.save()

    museums = Subject.objects.get(name='Музеї')
    museums.name = 'Музеєзнавство'
    museums.save()

    Subject(
        name='Літературознавство',
    ).save()
    Subject(
        name='Туризм',
    ).save()
    Subject(
        name='Архівознавство',
    ).save()
    Subject(
        name='Філателія',
    ).save()
    Subject(
        name='Соціологія',
    ).save()
    Subject(
        name='Засоби масової інформації',
    ).save()
    Subject(
        name='Нумізматика',
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('lgaapp', '0002_PredefinedFields'),
    ]

    operations = [
        migrations.RunPython(
            updates_to_subjects,
        ),
    ]
