# Generated by Django 3.2.13 on 2022-06-01 22:00

from django.db import migrations


def updates_to_arts(apps, schema_editor):
    Art = apps.get_model("lgaapp", "Art")

    Art(
        name='Образотворче мистецтво',
    ).save()
    Art(
        name='Дизайн',
    ).save()
    Art(
        name='Реставрація',
    ).save()
    Art(
        name='Охорона пам’яток мистецтва. Художні музеї. Колекції',
    ).save()
    Art(
        name='Антикваріат',
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('lgaapp', '0003_subjects_update'),
    ]

    operations = [
        migrations.RunPython(
            updates_to_arts,
        ),
    ]
