# Generated by Django 3.2.13 on 2022-06-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgaapp', '0004_arts_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
